title: NixOS Asahi Installer
description: NixOS installer for Apple Silicon Macs.
url: "https://nixos-asahi.qeden.dev"
author: Quinn Edenfield
email: quinn@qeden.dev
github_username: quinneden

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

favicon: assets/icons/favicon.svg
logo: assets/images/logo/nixos-asahi-logo-gray.svg

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - flake.lock
  - flake.nix
  - gemset.nix
  - package.nix
  - README.md
