baseURL = 'https://nixos-asahi.qeden.dev/'
languageCode = 'en-us'
title = "NixOS Asahi"
theme = "nightfall"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.header]]
name = "blog"
weight = 0
url = "blog"
[[menu.header]]
name = "about"
weight = 1
url = "about"

[params]
user = "nixos-asahi"
hostname = "qeden.dev"
[params.author]
name = "Quinn Edenfield"
email = "quinn@qeden.dev"

published = true

[[params.social]]
key = 0
name = "github"
url = "https://github.com/quinneden/nixos-asahi-package"
target = "_blank"
aria = "GitHub Repository"
