name: Deploy Jekyll site to Pages

"on":
  push:
    branches: [main]
    paths:
      - "**.nix"
      - .bundle/config
      - .github/workflows/github-pages.yaml
      - _config.yaml
      - _data/
      - _includes/
      - _layouts/
      - _sass/
      - assets
      - CNAME
      - flake.lock
      - Gemfile
      - Gemfile.lock
      - index.md
      - instructions.md
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: DeterminateSystems/nix-installer-action@v17
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Nix & Jekyll
        run: nix build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: result/srv

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    permissions:
      pages: write
      id-token: write
